import type { WidgetFile } from '../presentation/widgets/index.js';

export const START = '<!-- AWAKEN:START -->';
export const END = '<!-- AWAKEN:END -->';

const picture = (dir: string, file: WidgetFile, hasLight: boolean, width: string, alt: string): string => {
  const dark = `${dir}/${file.name}-dark.svg`;
  if (!hasLight) return `<img src="${dark}" width="${width}" alt="${alt}">`;
  return `<picture><source media="(prefers-color-scheme: dark)" srcset="${dark}"><source media="(prefers-color-scheme: light)" srcset="${dir}/${file.name}-light.svg"><img src="${dark}" width="${width}" alt="${alt}"></picture>`;
};

/** Full-width widgets get their own row; half-width ones pair up; runes go four to a row. */
export const buildBlock = (files: WidgetFile[], dir: string, hasLight: boolean, altFor: (f: WidgetFile) => string): string => {
  const rows: string[] = [];
  let pending: WidgetFile[] = [];
  const flush = () => {
    if (pending.length === 0) return;
    const width = pending[0]!.width <= 200 ? '24%' : '49%';
    rows.push(`<p align="center">\n${pending.map((f) => picture(dir, f, hasLight, width, altFor(f))).join('\n')}\n</p>`);
    pending = [];
  };
  for (const file of files) {
    if (file.width >= 800) {
      flush();
      rows.push(`<p align="center">\n${picture(dir, file, hasLight, '100%', altFor(file))}\n</p>`);
      continue;
    }
    if (pending.length && pending[0]!.width !== file.width) flush();
    pending.push(file);
    if ((file.width <= 200 && pending.length === 4) || (file.width > 200 && pending.length === 2)) flush();
  }
  flush();
  return `${START}\n<!-- Generated by git-profile-awaken. Edit awaken.json instead of this block. -->\n${rows.join('\n\n')}\n${END}`;
};

/** Replaces the marked block, or appends one when the README has no markers yet. */
export const injectBlock = (readme: string, block: string): { text: string; appended: boolean } => {
  const start = readme.indexOf(START);
  const end = readme.indexOf(END);
  if (start !== -1 && end > start) {
    return { text: readme.slice(0, start) + block + readme.slice(end + END.length), appended: false };
  }
  return { text: `${readme.trimEnd()}\n\n${block}\n`, appended: true };
};
