import type { WidgetFile } from '../presentation/widgets/index.js';

export const START = '<!-- AWAKEN:START -->';
export const END = '<!-- AWAKEN:END -->';

const picture = (dir: string, file: WidgetFile, hasLight: boolean, width: string, alt: string): string => {
  const dark = `${dir}/${file.name}-dark.svg`;
  const img = `<img src="${dark}" width="${width}" alt="${alt}">`;
  const pic = hasLight
    ? `<picture><source media="(prefers-color-scheme: dark)" srcset="${dark}"><source media="(prefers-color-scheme: light)" srcset="${dir}/${file.name}-light.svg">${img}</picture>`
    : img;
  return file.href ? `<a href="${file.href.replace(/"/g, '%22')}">${pic}</a>` : pic;
};

const widthOf = (file: WidgetFile): string => (file.width >= 800 ? '100%' : file.width <= 200 ? '24%' : '49%');

/** One centered paragraph per line of images; lines come from the layout. */
export const buildBlock = (rows: WidgetFile[][], dir: string, hasLight: boolean, altFor: (f: WidgetFile) => string): string => {
  const lines = rows.filter((row) => row.length).map((row) => `<p align="center">\n${row.map((f) => picture(dir, f, hasLight, widthOf(f), altFor(f))).join('\n')}\n</p>`);
  return `${START}\n<!-- Generated by git-profile-awaken. Edit awaken.json instead of this block. -->\n${lines.join('\n\n')}\n${END}`;
};

/** Replaces the marked block, or appends one when the README has no markers yet. */
export const injectBlock = (readme: string, block: string): { text: string; appended: boolean } => {
  const start = readme.indexOf(START);
  const end = readme.indexOf(END);
  if (start !== -1 && end > start) {
    return { text: readme.slice(0, start) + block + readme.slice(end + END.length), appended: false };
  }
  return { text: `${readme.trimEnd()}\n\n${block}\n`, appended: true };
};
