// Fits the rank model to the sample from scripts/sample-population.ts and writes src/application/populationData.ts.
// Only aggregate numbers are written; the per-player sample stays out of the repository.
import { readFile, writeFile } from 'node:fs/promises';
import { STAT_CODES, type StatCode } from '../src/domain/types.js';
import { compositeScore, percentileOf, type Population, type StatDistribution } from '../src/application/population.js';

type Row = Record<StatCode, number> & { yearContributions: number };
/** Ranks compare against regular players: at least this many contributions in the past year. */
const REGULAR = 10;
const parsed = (await readFile('data/population-sample.jsonl', 'utf8')).split(/\r?\n/).flatMap((line) => {
  try {
    return line ? [JSON.parse(line) as Row & { login: string }] : [];
  } catch {
    return [];
  }
});
const all = [...new Map(parsed.map((r) => [r.login, r])).values()];
const rows = all.filter((r) => r.yearContributions >= REGULAR);
if (rows.length < 200) throw new Error(`Only ${rows.length} samples; collect more first.`);

const fit = (values: number[]): StatDistribution => {
  const positive = values.filter((v) => v > 0).map((v) => Math.log1p(v));
  const mu = positive.reduce((s, v) => s + v, 0) / positive.length;
  const sigma = Math.sqrt(positive.reduce((s, v) => s + (v - mu) ** 2, 0) / (positive.length - 1));
  return { zero: (values.length - positive.length) / values.length, mu, sigma };
};

const stats = Object.fromEntries(STAT_CODES.map((code) => [code, fit(rows.map((r) => r[code]))])) as Record<StatCode, StatDistribution>;

const scores = rows
  .map((r) => compositeScore(Object.fromEntries(STAT_CODES.map((c) => [c, percentileOf(r[c], stats[c])])) as Record<StatCode, number>))
  .sort((a, b) => a - b);
const composite = Array.from({ length: 201 }, (_, i) => {
  const pos = (i / 200) * (scores.length - 1);
  const lo = Math.floor(pos);
  const hi = Math.min(scores.length - 1, lo + 1);
  return Number((scores[lo]! + (scores[hi]! - scores[lo]!) * (pos - lo)).toFixed(5));
});

const round = (d: StatDistribution): StatDistribution => ({ zero: Number(d.zero.toFixed(4)), mu: Number(d.mu.toFixed(4)), sigma: Number(d.sigma.toFixed(4)) });
const population: Population = {
  sampledAt: new Date().toISOString().slice(0, 10),
  size: rows.length,
  stats: Object.fromEntries(STAT_CODES.map((c) => [c, round(stats[c])])) as Record<StatCode, StatDistribution>,
  composite,
};

await writeFile('src/application/populationData.ts', `// Generated by scripts/fit-population.ts from ${rows.length} randomly sampled GitHub accounts with at least ${REGULAR}
// contributions in the past year (out of ${all.length} sampled accounts with any). Aggregates only. Refresh with: npm run sample-population && npm run fit-population
import type { Population } from './population.js';

export const POPULATION: Population = ${JSON.stringify(population, null, 2)};
`);

const median = (c: StatCode) => {
  const v = rows.map((r) => r[c]).sort((a, b) => a - b);
  return v[Math.floor(v.length / 2)];
};
console.log(`${rows.length} players. Medians: ${STAT_CODES.map((c) => `${c} ${median(c)}`).join(', ')}`);
for (const c of STAT_CODES) console.log(c, JSON.stringify(population.stats[c]));
