// Candidate simple-icons slugs for the Arsenal, by category. vendor-brand-icons.mjs keeps the ones that exist.
export const TECH_CATEGORIES = {
  'Game development': [
    'unity', 'unrealengine', 'godotengine', 'gamemaker', 'defold', 'cocos', 'construct3', 'rpgmaker', 'renpy', 'pygame',
    'bevy', 'monogame', 'love', 'phaser', 'babylondotjs', 'threedotjs', 'playcanvas', 'aseprite', 'tiled', 'ldtk',
    'spine', 'fmod', 'audiokinetic', 'steam', 'steamdeck', 'itchdotio', 'epicgames', 'gogdotcom', 'playstation',
    'xbox', 'nintendoswitch', 'nintendo', 'roblox', 'robloxstudio', 'minecraft', 'curseforge', 'modrinth', 'valve',
    'opengl', 'vulkan', 'webgl', 'webgpu', 'directx', 'khronosgroup', 'nvidia', 'amd', 'intel', 'meta', 'oculus',
    'htcvive', 'pico', 'arm', 'qualcomm', 'photon', 'mirror', 'playfab', 'gameanalytics', 'appsflyer', 'unity3d',
  ],
  Languages: [
    'typescript', 'javascript', 'python', 'cplusplus', 'c', 'csharp', 'dotnet', 'rust', 'go', 'kotlin', 'swift', 'dart',
    'php', 'ruby', 'lua', 'gnubash', 'powershell', 'haskell', 'elixir', 'erlang', 'scala', 'clojure', 'fsharp', 'ocaml',
    'julia', 'r', 'perl', 'zig', 'nim', 'crystal', 'v', 'odin', 'gleam', 'elm', 'purescript', 'reason', 'rescript',
    'solidity', 'assemblyscript', 'webassembly', 'fortran', 'cobol', 'lisp', 'commonlisp', 'racket', 'scheme',
    'prolog', 'groovy', 'apachegroovy', 'coffeescript', 'livescript', 'mojo', 'carbon', 'd', 'ada', 'pascal',
    'delphi', 'matlab', 'mathworks', 'labview', 'wolframlanguage', 'wolframmathematica', 'gdscript', 'haxe', 'vala',
    'openjdk', 'java', 'kotlin', 'objectivec', 'graphql', 'markdown', 'latex', 'mdx', 'json', 'yaml', 'toml', 'xml',
  ],
  Frontend: [
    'react', 'nextdotjs', 'vuedotjs', 'nuxt', 'nuxtdotjs', 'angular', 'angularjs', 'svelte', 'solid', 'preact', 'qwik',
    'astro', 'remix', 'gatsby', 'eleventy', 'hugo', 'jekyll', 'docusaurus', 'vitepress', 'ember', 'emberdotjs',
    'alpinedotjs', 'htmx', 'lit', 'stencil', 'storybook', 'redux', 'mobx', 'reactquery', 'tanstack', 'reactrouter',
    'zod', 'tailwindcss', 'bootstrap', 'bulma', 'sass', 'less', 'stylus', 'postcss', 'styledcomponents', 'emotion',
    'chakraui', 'mui', 'antdesign', 'shadcnui', 'radixui', 'daisyui', 'headlessui', 'framer', 'greensock', 'd3',
    'chartdotjs', 'apacheecharts', 'leaflet', 'mapbox', 'jquery', 'webpack', 'vite', 'rollupdotjs', 'esbuild',
    'parcel', 'babel', 'swc', 'turborepo', 'nx', 'pnpm', 'yarn', 'npm', 'bun', 'deno', 'html5', 'css', 'css3',
    'javascript', 'typescript', 'pwa', 'webcomponentsdotorg', 'electron', 'tauri', 'capacitor', 'ionic',
  ],
  Backend: [
    'nodedotjs', 'express', 'fastify', 'nestjs', 'koa', 'hono', 'adonisjs', 'django', 'flask', 'fastapi', 'pydantic',
    'celery', 'spring', 'springboot', 'quarkus', 'micronaut', 'dotnet', 'blazor', 'laravel', 'symfony', 'codeigniter',
    'rubyonrails', 'sinatra', 'phoenixframework', 'gin', 'fiber', 'echo', 'actix', 'rocket', 'axum', 'graphql',
    'apollographql', 'trpc', 'grpc', 'swagger', 'openapiinitiative', 'postman', 'insomnia', 'nginx', 'apache',
    'caddy', 'traefikproxy', 'rabbitmq', 'apachekafka', 'nats', 'socketdotio', 'stripe', 'paypal', 'twilio',
    'auth0', 'clerk', 'keycloak', 'okta', 'jsonwebtokens', 'passport', 'prisma', 'drizzle', 'sequelize', 'typeorm',
    'mongoose', 'sqlalchemy', 'hibernate', 'gradle', 'apachemaven', 'composer', 'pypi', 'poetry', 'uv', 'conda',
  ],
  Mobile: [
    'android', 'androidstudio', 'ios', 'apple', 'xcode', 'swift', 'kotlin', 'flutter', 'dart', 'reactnative',
    'expo', 'ionic', 'capacitor', 'jetpackcompose', 'swiftui', 'xamarin', 'dotnetmaui', 'appstore',
    'googleplay', 'fastlane', 'testflight', 'huawei', 'samsung', 'xiaomi',
  ],
  'Cloud and DevOps': [
    'docker', 'kubernetes', 'helm', 'podman', 'terraform', 'pulumi', 'ansible', 'chef', 'puppet', 'vagrant',
    'packer', 'consul', 'vault', 'nomad', 'hashicorp', 'googlecloud', 'microsoftazure', 'digitalocean', 'linode',
    'akamai', 'hetzner', 'vultr', 'ovh', 'cloudflare', 'cloudflarepages', 'cloudflareworkers', 'vercel', 'netlify',
    'render', 'railway', 'flydotio', 'heroku', 'firebase', 'supabase', 'appwrite', 'pocketbase', 'githubactions',
    'gitlab', 'jenkins', 'circleci', 'travisci', 'argo', 'fluxcd', 'githubpages', 'grafana', 'prometheus',
    'datadog', 'newrelic', 'sentry', 'elastic', 'kibana', 'logstash', 'opentelemetry', 'jaeger', 'splunk',
    'pagerduty', 'nginx', 'linux', 'ubuntu', 'debian', 'fedora', 'redhat', 'centos', 'archlinux', 'alpinelinux',
    'nixos', 'githubcopilot', 'dependabot', 'renovate',
    'sonarqube', 'snyk', 'trivy', 'minio', 'ceph', 'openstack', 'proxmox', 'vmware', 'virtualbox', 'qemu',
  ],
  'Data and AI': [
    'pytorch', 'tensorflow', 'keras', 'scikitlearn', 'numpy', 'pandas', 'polars', 'scipy', 'jupyter', 'anaconda',
    'googlecolab', 'kaggle', 'huggingface', 'langchain', 'llamaindex', 'ollama', 'anthropic', 'claude', 'googlegemini',
    'mistralai', 'perplexity', 'replicate', 'nvidia', 'opencv', 'mediapipe', 'onnx', 'tensorrt', 'mlflow',
    'weightsandbiases', 'dvc', 'apachespark', 'apacheairflow', 'apachehadoop', 'apacheflink', 'databricks',
    'snowflake', 'dbt', 'apachesuperset', 'metabase', 'tableau', 'powerbi', 'looker', 'plotly', 'streamlit',
    'gradio', 'dask', 'ray', 'xgboost', 'lightgbm', 'spacy', 'nltk', 'openaigym', 'deepnote', 'rstudioide', 'jax',
  ],
  Databases: [
    'postgresql', 'mysql', 'mariadb', 'sqlite', 'mongodb', 'redis', 'valkey', 'cassandra', 'apachecassandra',
    'couchbase', 'couchdb', 'neo4j', 'elasticsearch', 'opensearch', 'meilisearch', 'algolia', 'typesense',
    'clickhouse', 'duckdb', 'cockroachlabs', 'planetscale', 'neon', 'turso', 'surrealdb', 'influxdb', 'timescale',
    'dynamodb', 'firebase', 'supabase', 'prisma', 'oracle', 'microsoftsqlserver', 'pinecone', 'qdrant', 'milvus',
    'weaviate', 'chroma', 'dbeaver', 'datagrip',
  ],
  'Design and UI/UX': [
    'figma', 'sketch', 'framer', 'penpot', 'invision', 'zeplin', 'protopie', 'miro', 'whimsical', 'excalidraw',
    'tldraw', 'drawdotio', 'diagramsdotnet', 'lucid', 'balsamiq', 'principle', 'spline', 'rive', 'lottiefiles',
    'webflow', 'wix', 'squarespace', 'dribbble', 'behance', 'awwwards', 'pinterest', 'unsplash', 'pexels',
    'googlefonts', 'fontawesome', 'iconify', 'materialdesign', 'materialdesignicons', 'storybook', 'gimp',
    'inkscape', 'krita', 'affinitydesigner', 'affinityphoto', 'affinitypublisher', 'affinity', 'pixlr', 'photopea',
    'coreldraw', 'clipstudiopaint', 'procreate', 'notion', 'readdotcv', 'hotjar', 'maze', 'useberry',
  ],
  '3D, VFX and animation': [
    'blender', 'autodesk', 'autodeskmaya', 'autodesk3dsmax', 'houdini', 'cinema4d', 'maxon', 'zbrush', 'substance3d',
    'marmoset', 'sketchfab', 'unity', 'unrealengine', 'nvidia', 'redshift', 'octanerender', 'vray', 'keyshot',
    'sketchup', 'fusion360', 'autocad', 'solidworks', 'freecad', 'openscad', 'rhinoceros', 'daz3d', 'meshroom',
    'polycam', 'kitbash3d', 'mixamo', 'adobe', 'spine', 'moho', 'toonboom', 'opentoonz', 'synfig',
  ],
  'Audio and video': [
    'davinciresolve', 'blackmagicdesign', 'obsstudio', 'kdenlive', 'shotcut', 'openshot', 'capcut', 'finalcutpro',
    'imovie', 'audacity', 'ableton', 'abletonlive', 'flstudio', 'imageline', 'reaper', 'cockos', 'steinberg',
    'protools', 'avid', 'logicpro', 'garageband', 'fmod', 'audiokinetic', 'spotify', 'soundcloud', 'youtube',
    'twitch', 'streamlabs', 'elgato', 'ffmpeg', 'vlcmediaplayer', 'handbrake', 'descript',
  ],
  'Editors and tools': [
    'neovim', 'vim', 'gnuemacs', 'sublimetext', 'zedindustries', 'cursor', 'windsurf', 'jetbrains', 'intellijidea',
    'pycharm', 'webstorm', 'phpstorm', 'rider', 'clion', 'goland', 'rubymine', 'datagrip', 'fleet', 'androidstudio',
    'xcode', 'eclipseide', 'netbeans', 'notepadplusplus', 'jupyter', 'replit', 'codesandbox', 'stackblitz',
    'codepen', 'glitch', 'gitkraken', 'git', 'github', 'bitbucket', 'gitea', 'sourcetree', 'githubdesktop', 'gitlab', 'warp', 'iterm2', 'windowsterminal',
    'alacritty', 'kitty', 'wezterm', 'tmux', 'zsh', 'ohmyzsh', 'fishshell', 'homebrew', 'chocolatey', 'scoop',
    'raycast', 'alfred', 'obsidian', 'logseq', 'notion', 'jira', 'confluence', 'trello', 'asana', 'clickup',
    'linear', 'mondaydotcom', 'slack', 'discord', 'zoom', 'googlemeet', 'microsoftteams', 'loom', 'airtable',
    'zapier', 'make', 'n8n', 'ifttt', 'postman', 'insomnia', 'hoppscotch', 'bruno', 'wireshark', 'charles',
  ],
  Testing: [
    'jest', 'vitest', 'mocha', 'chai', 'jasmine', 'cypress', 'playwright', 'puppeteer', 'selenium', 'webdriverio',
    'testinglibrary', 'pytest', 'junit5', 'testng', 'cucumber', 'k6', 'gatling', 'apachejmeter', 'locust',
    'postman', 'browserstack', 'saucelabs', 'lighthouse', 'eslint', 'prettier', 'biome', 'stylelint', 'husky',
    'commitlint', 'sonarcloud', 'codecov', 'coveralls', 'storybook', 'chromatic',
  ],
  'Web3 and blockchain': [
    'ethereum', 'bitcoin', 'solana', 'polygon', 'chainlink', 'binance', 'coinbase', 'metamask', 'web3dotjs',
    'ethers', 'hardhat', 'foundry', 'truffle', 'ipfs', 'opensea', 'cardano', 'polkadot', 'tether', 'near', 'sui',
  ],
  'Hardware and embedded': [
    'arduino', 'raspberrypi', 'espressif', 'stmicroelectronics', 'platformio', 'micropython', 'circuitpython',
    'adafruit', 'sparkfun', 'kicad', 'autodesk', 'nvidia', 'intel', 'amd', 'arm', 'riscv', 'linux', 'freertos',
    'zephyrproject', 'ros', 'homeassistant', 'tasmota', 'esphome', 'thingiverse', 'prusa', 'bambulab', 'ultimaker',
  ],
  'CMS and commerce': [
    'wordpress', 'woocommerce', 'shopify', 'magento', 'prestashop', 'drupal', 'joomla', 'ghost', 'strapi', 'sanity',
    'contentful', 'directus', 'payloadcms', 'storyblok', 'keystone', 'medusa', 'bigcommerce', 'squarespace', 'wix',
    'webflow', 'hashnode', 'medium', 'substack', 'devdotto', 'gumroad', 'lemonsqueezy', 'paddle',
  ],
  'Operating systems': [
    'linux', 'ubuntu', 'debian', 'fedora', 'archlinux', 'manjaro', 'linuxmint', 'popos', 'kalilinux', 'opensuse',
    'gentoo', 'nixos', 'alpinelinux', 'freebsd', 'openbsd', 'macos', 'apple', 'ios', 'android', 'chromeos',
    'harmonyos', 'steamdeck', 'raspberrypi', 'windows', 'windows11', 'windows10',
  ],
};
